# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0002_auto_20170628_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerlog',
            name='last_processed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='providerlog',
            name='uuid4',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
