version: '3.1'

services:

# MAIN WEB CONTAINER
  poster_web:
    container_name: poster_web
    build: .
    image: poster-web:latest
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - .:/code
      - poster_media_data:/media
    depends_on:
      - poster_postgres
      - poster_redis
      - poster_mongo

# CELERY WORKER AND BEAT CONTAINERS derived from above
  poster_celery_worker:
    container_name: poster_celery_worker
    image: poster-web:latest
    command: python -m celery -A poster worker -l debug
    env_file: .env
    volumes:
      - poster_media_data
    depends_on:
      - poster_web

  poster_celery_beat:
    container_name: poster_celery_beat
    image: poster-web:latest
    command: python -m celery -A poster beat --pidfile= -l debug
    env_file: .env
    volumes:
      - poster_media_data
    depends_on:
      - poster_web

# POSTGRES, REDIS, MONGO DB CONTAINERS
  poster_postgres:
    container_name: poster_postgres
    image: mdillon/postgis:9.5
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - poster_postgres_data:/var/lib/postgresql/data/

  poster_redis:
    container_name: poster_redis
    image: redis:3.0.0
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - poster_redis_data:/data

  poster_mongo:
    container_name: poster_mongo
    image: mongo:3.2
    command: --storageEngine wiredTiger
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - poster_mongo_data:/data/db

# VOLUMES DEFINITION
volumes:
  poster_postgres_data:
  poster_redis_data:
  poster_mongo_data:
  poster_media_data: