# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 13:39
from __future__ import unicode_literals

from django.db import migrations

from apps.common.models import Property, Process
from apps.utils.obj import get_or_create_objs

processes_def = [
    ('measure', {'name': u'measuring'}),
    ('avg_hour', {'name': u'hourly average'}),
    ('avg_day', {'name': u'daily average'}),
]

props_def = [
    ('precipitation',           {"name": 'precipitation', 'unit': 'mm'}),
    ('air_temperature',         {"name": 'air temperature', 'unit': '°C'}),
    ('air_humidity',            {"name": 'air humidity', 'unit': '?'}),
    ('ground_air_temperature',  {"name": 'ground air temperature', 'unit': '°C'}),
    ('soil_temperature',        {"name": 'soil temperature', 'unit': '°C'}),
    ('power_voltage',           {"name": 'power voltage', 'unit': 'V'}),
]


def load_data(apps, schema_editor):
    get_or_create_objs(Property, props_def, 'name_id')
    get_or_create_objs(Process, processes_def, 'name_id')


def delete_data(apps, schema_editor):

    Property_model = apps.get_model("common", "Property")
    Property_model.objects.all().delete()

    Process_model = apps.get_model("common", "Process")
    Process_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data),
        # migrations.RunPython(load_properties, delete_properties),
    ]
