# Generated by Django 2.1.5 on 2019-03-20 14:53

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mc', '0001_create_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesFeature',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_by_provider', models.CharField(editable=False, help_text='ID of the station used by provider.', max_length=50)),
                ('name', models.CharField(help_text='Human-readable name of the station.', max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Spatial information about feature.', srid=4326)),
                ('content', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
