# Generated by Django 2.1.11 on 2019-10-22 11:42

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0008_timeslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenomenon_time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='Datetime range when the observation was captured.')),
                ('result', models.DecimalField(decimal_places=3, editable=False, help_text='Numerical value of the measured phenomenon in units specified by Process.', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_null_reason', models.CharField(default='', help_text='Reason why result is null.', max_length=100)),
            ],
            options={
                'ordering': ['-phenomenon_time_range', 'feature_of_interest', 'procedure', 'observed_property'],
                'get_latest_by': 'phenomenon_time_range',
            },
        ),
        migrations.CreateModel(
            name='SamplingFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_by_provider', models.CharField(editable=False, help_text='ID of the station used by provider.', max_length=50)),
                ('name', models.CharField(help_text='Human-readable name of the station.', max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Spatial information about feature.', srid=3857)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='feature_of_interest',
            field=models.ForeignKey(editable=False, help_text='Watercourse station where the observation was taken.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='observations', to='huaihe.SamplingFeature'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observed_property',
            field=models.ForeignKey(editable=False, help_text='Phenomenon that was observed, e.g. air temperature.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='huaihe_observation_related', to='common.Property'),
        ),
        migrations.AddField(
            model_name='observation',
            name='procedure',
            field=models.ForeignKey(editable=False, help_text='Process used to generate the result, e.g. measurement or average.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='huaihe_observation_related', to='common.Process'),
        ),
        migrations.AddField(
            model_name='observation',
            name='related_observations',
            field=models.ManyToManyField(editable=False, help_text='Measured observations that were used to generate average observation, or vice versa.', related_name='_observation_related_observations_+', to='huaihe.Observation'),
        ),
        migrations.AddField(
            model_name='observation',
            name='time_slots',
            field=models.ForeignKey(default=None, help_text='Time_slots used to calc aggregations', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='huaihe_observation_related', to='common.TimeSlots'),
        ),
        migrations.RunSQL("""
               	CREATE UNIQUE INDEX huaihe_observation_uniq ON huaihe_observation
    			    (
    			        phenomenon_time_range, 
    			        observed_property_id, 
    			        feature_of_interest_id, 
    			        procedure_id, 
    			        COALESCE(time_slots_id, -1)
    			    );
            """),
    ]
