# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

from apps.importing.models import ProviderLog


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0002_auto_20170628_2316'),
    ]

    # def gen_uuid(apps, schema_editor):
    #     for row in ProviderLog.objects.all():
    #         row.uuid4 = uuid.uuid4()
    #         row.save()

    operations = [
        migrations.AddField(
            model_name='providerlog',
            name='last_processed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        #
        # migrations.RunPython(gen_uuid),
        #
        migrations.AddField(
            model_name='providerlog',
            name='uuid4',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
