# Generated by Django 2.0.2 on 2018-02-13 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0003_auto_20170803_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerlog',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='importing.Provider'),
        ),
    ]
