# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilityObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('phenomenon_time', models.DateTimeField(editable=False,
                                                         help_text='Beginning of the observation.')),
                ('phenomenon_time_to', models.DateTimeField(editable=False,
                                                            help_text='End of the observation.')),
                ('src_occurrence_type', models.CharField(
                    choices=[('0', 'Any'),
                             ('1', 'Transit'),
                             ('2', 'Visit')], default='0',
                    help_text='Occurrence type in the source ZSJ.',
                    max_length=1)),
                ('dst_occurrence_type', models.CharField(
                    choices=[('0', 'Any'),
                             ('1', 'Transit'),
                             ('2', 'Visit')], default='0',
                    help_text='Occurrence type in the destination ZSJ.',
                    max_length=1)),
                ('uniques_type',
                 models.CharField(choices=[('0', 'All'), ('1', 'Uniques')],
                                  default='0',
                                  help_text='All or only uniques.',
                                  max_length=1)),
                ('result', models.PositiveIntegerField(editable=False,
                                                       help_text='Numerical value of the measured phenomenon in units specified by Process.',
                                                       null=True)),
                ('result_null_reason',
                 models.CharField(help_text='Reason why result is null.',
                                  max_length=100)),
            ],
            options={
                'ordering': ['-phenomenon_time', 'feature_of_interest',
                             'procedure', 'observed_property'],
                'get_latest_by': 'phenomenon_time',
            },
        ),
        migrations.CreateModel(
            name='MobilityStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['src_zsj__name', 'dst_zsj__name'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(editable=False,
                                             help_text='Unique and computer-friendly name of the process.',
                                             max_length=30, unique=True)),
                ('name', models.CharField(
                    help_text='Human-readable name of the process.',
                    max_length=100)),
            ],
            options={
                'verbose_name_plural': 'processes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(editable=False,
                                             help_text='Unique and computer-friendly name of the property.',
                                             max_length=30, unique=True)),
                ('name', models.CharField(
                    help_text='Human-readable name of the property.',
                    max_length=100)),
                ('unit', models.CharField(
                    help_text='Unit of observations (physical unit). Same for all observations of the property.',
                    max_length=30)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zsj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('id_by_provider', models.CharField(editable=False,
                                                    help_text='ID of the ZSJ used by Czech law.',
                                                    max_length=100)),
                ('name',
                 models.CharField(help_text='Human-readable name of the ZSJ.',
                                  max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mobilitystream',
            name='dst_zsj',
            field=models.ForeignKey(editable=False,
                                    help_text='Destination ZSJ, where people are arriving.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='to_streams', to='o2.Zsj'),
        ),
        migrations.AddField(
            model_name='mobilitystream',
            name='opposite',
            field=models.OneToOneField(editable=False,
                                       help_text='Stream in opposite direction to this stream.',
                                       null=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       to='o2.MobilityStream'),
        ),
        migrations.AddField(
            model_name='mobilitystream',
            name='src_zsj',
            field=models.ForeignKey(editable=False,
                                    help_text='Source ZSJ, where people are departing.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='arrival_streams',
                                    to='o2.Zsj'),
        ),
        migrations.AddField(
            model_name='mobilityobservation',
            name='feature_of_interest',
            field=models.ForeignKey(editable=False,
                                    help_text='Stream station where the observation was taken.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='observations',
                                    to='o2.MobilityStream'),
        ),
        migrations.AddField(
            model_name='mobilityobservation',
            name='observed_property',
            field=models.ForeignKey(editable=False,
                                    help_text='Phenomenon that was observed, e.g. mobility.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='observations',
                                    to='o2.Property'),
        ),
        migrations.AddField(
            model_name='mobilityobservation',
            name='procedure',
            field=models.ForeignKey(editable=False,
                                    help_text='Process used to generate the result, e.g. estimation.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='observations',
                                    to='o2.Process'),
        ),
        migrations.AlterUniqueTogether(
            name='mobilitystream',
            unique_together=set([('src_zsj', 'dst_zsj')]),
        ),
        migrations.AlterUniqueTogether(
            name='mobilityobservation',
            unique_together=set([('phenomenon_time', 'phenomenon_time_to',
                                  'observed_property', 'feature_of_interest',
                                  'procedure', 'src_occurrence_type',
                                  'dst_occurrence_type', 'uniques_type')]),
        ),
    ]
