# Generated by Django 2.0.2 on 2018-02-13 23:43

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0003_mobility_common_property_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilityobservation',
            name='related_observations',
            field=models.ManyToManyField(editable=False, help_text='Measured observations that were used to generate average observation, or vice versa.', related_name='_mobilityobservation_related_observations_+', to='o2.MobilityObservation'),
        ),
        migrations.AlterField(
            model_name='mobilityobservation',
            name='feature_of_interest',
            field=models.ForeignKey(editable=False, help_text='Stream station where the observation was taken.', on_delete=django.db.models.deletion.DO_NOTHING, to='o2.MobilityStream'),
        ),
        migrations.AlterField(
            model_name='mobilityobservation',
            name='observed_property',
            field=models.ForeignKey(editable=False, help_text='Phenomenon that was observed, e.g. air temperature.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='o2_mobilityobservation_related', to='common.Property'),
        ),
        migrations.AlterField(
            model_name='mobilityobservation',
            name='phenomenon_time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='Datetime range when the observation was captured.'),
        ),
        migrations.AlterField(
            model_name='mobilityobservation',
            name='procedure',
            field=models.ForeignKey(editable=False, help_text='Process used to generate the result, e.g. measurement or average.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='o2_mobilityobservation_related', to='common.Process'),
        ),
        migrations.AlterField(
            model_name='mobilityobservation',
            name='result_null_reason',
            field=models.CharField(default='', help_text='Reason why result is null.', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilitystream',
            name='dst_zsj',
            field=models.ForeignKey(editable=False, help_text='Destination ZSJ, where people are arriving.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_streams', to='o2.Zsj'),
        ),
        migrations.AlterField(
            model_name='mobilitystream',
            name='opposite',
            field=models.OneToOneField(editable=False, help_text='Stream in opposite direction to this stream.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='o2.MobilityStream'),
        ),
        migrations.AlterField(
            model_name='mobilitystream',
            name='src_zsj',
            field=models.ForeignKey(editable=False, help_text='Source ZSJ, where people are departing.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_streams', to='o2.Zsj'),
        ),
        migrations.AlterField(
            model_name='sociodemoobservation',
            name='feature_of_interest',
            field=models.ForeignKey(editable=False, help_text='ZSJ where the observation was taken.', on_delete=django.db.models.deletion.DO_NOTHING, to='o2.Zsj'),
        ),
        migrations.AlterField(
            model_name='sociodemoobservation',
            name='observed_property',
            field=models.ForeignKey(editable=False, help_text='Phenomenon that was observed, e.g. air temperature.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='o2_sociodemoobservation_related', to='common.Property'),
        ),
        migrations.AlterField(
            model_name='sociodemoobservation',
            name='procedure',
            field=models.ForeignKey(editable=False, help_text='Process used to generate the result, e.g. measurement or average.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='o2_sociodemoobservation_related', to='common.Process'),
        ),
    ]
