# Generated by Django 2.0.3 on 2018-08-08 11:55

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0004_auto_20180214_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilityobservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilityobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sociodemoobservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sociodemoobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunSQL("UPDATE o2_mobilityobservation "
                          "SET created_at=CURRENT_TIMESTAMP"
                          ", updated_at=CURRENT_TIMESTAMP"),
        migrations.RunSQL("UPDATE o2_sociodemoobservation "
                          "SET created_at=CURRENT_TIMESTAMP"
                          ", updated_at=CURRENT_TIMESTAMP"),
    ]
