# Generated by Django 2.1.5 on 2019-03-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_timeslots'),
        ('o2', '0007_created_updated_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilityobservation',
            name='time_slots',
            field=models.ForeignKey(default=None, help_text='Time_slots used to calc aggregations', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='o2_mobilityobservation_related', to='common.TimeSlots'),
        ),
        migrations.AddField(
            model_name='sociodemoobservation',
            name='time_slots',
            field=models.ForeignKey(default=None, help_text='Time_slots used to calc aggregations', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='o2_sociodemoobservation_related', to='common.TimeSlots'),
        ),
        migrations.AlterUniqueTogether(
            name='mobilityobservation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sociodemoobservation',
            unique_together=set(),
        ),
    ]
