# Generated by Django 2.1.5 on 2019-03-25 14:08

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0008_add_timeslots_delete_unique'),
    ]

    operations = [
        migrations.RunSQL("""
        	DELETE FROM o2_mobilityobservation_related_observations 
				WHERE from_mobilityobservation_id IN (
				    SELECT id FROM o2_mobilityobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM o2_mobilityobservation_related_observations 
				WHERE to_mobilityobservation_id IN (
				    SELECT id FROM o2_mobilityobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM o2_mobilityobservation WHERE procedure_id IN (
			    SELECT id FROM common_process WHERE name_id IN (
			        'apps.common.aggregate.sum_total', 
			        'apps.common.aggregate.circle_mean', 
			        'apps.common.aggregate.arithmetic_mean', 
			        'avg_day',
			        'avg_hour'
			    )
			);
        """),
        migrations.RunSQL("""
        	CREATE UNIQUE INDEX o2_mobilityobservation_uniq ON o2_mobilityobservation
			    (
			        phenomenon_time_range, 
			        observed_property_id, 
			        feature_of_interest_id, 
			        procedure_id, 
                    src_occurrence_type,
                    dst_occurrence_type,
                    uniques_type,
			        COALESCE(time_slots_id, -1)
			    );
        """),


        migrations.RunSQL("""
        	DELETE FROM o2_sociodemoobservation_related_observations 
				WHERE from_sociodemoobservation_id IN (
				    SELECT id FROM o2_sociodemoobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM o2_sociodemoobservation_related_observations 
				WHERE to_sociodemoobservation_id IN (
				    SELECT id FROM o2_sociodemoobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM o2_sociodemoobservation WHERE procedure_id IN (
			    SELECT id FROM common_process WHERE name_id IN (
			        'apps.common.aggregate.sum_total', 
			        'apps.common.aggregate.circle_mean', 
			        'apps.common.aggregate.arithmetic_mean', 
			        'avg_day',
			        'avg_hour'
			    )
			);
        """),
        migrations.RunSQL("""
        	CREATE UNIQUE INDEX o2_sociodemoobservation_uniq ON o2_sociodemoobservation
			    (
			        phenomenon_time_range, 
			        observed_property_id, 
			        feature_of_interest_id, 
			        procedure_id, 
                    age,
                    gender,
                    occurrence_type,
			        COALESCE(time_slots_id, -1)
			    );
        """),
    ]
