# Generated by Django 2.1.5 on 2019-03-25 14:08

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0009_delete_agg_create_unique_index'),
    ]

    operations = [
        migrations.RunSQL("""
        	TRUNCATE o2_mobilityobservation_related_observations;
        """),
        migrations.RunSQL("""
        	TRUNCATE o2_sociodemoobservation_related_observations;
        """),
    ]
