# Generated by Django 2.0.3 on 2018-09-17 17:46

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_time_range_custom_functions'),
        ('pmo', '0004_created_updated_notnull'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenomenon_time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='Datetime range when the observation was captured.')),
                ('result', models.DecimalField(decimal_places=3, editable=False, help_text='Numerical value of the measured phenomenon in units specified by Process.', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_null_reason', models.CharField(default='', help_text='Reason why result is null.', max_length=100)),
            ],
            options={
                'ordering': ['-phenomenon_time_range', 'feature_of_interest', 'procedure', 'observed_property'],
                'get_latest_by': 'phenomenon_time_range',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_by_provider', models.CharField(editable=False, help_text='ID of the station used by provider.', max_length=50)),
                ('name', models.CharField(help_text='Human-readable name of the station.', max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='feature_of_interest',
            field=models.ForeignKey(editable=False, help_text='Weather station where the observation was taken.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pmo_weatherobservation_related', to='pmo.WeatherStation'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='observed_property',
            field=models.ForeignKey(editable=False, help_text='Phenomenon that was observed, e.g. air temperature.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pmo_weatherobservation_related', to='common.Property'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='procedure',
            field=models.ForeignKey(editable=False, help_text='Process used to generate the result, e.g. measurement or average.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pmo_weatherobservation_related', to='common.Process'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='related_observations',
            field=models.ManyToManyField(editable=False, help_text='Measured observations that were used to generate average observation, or vice versa.', related_name='_weatherobservation_related_observations_+', to='pmo.WeatherObservation'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherobservation',
            unique_together={('phenomenon_time_range', 'observed_property', 'feature_of_interest', 'procedure')},
        ),
    ]
