# Generated by Django 2.0.8 on 2018-11-06 15:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0005_auto_20180917_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='basin',
            field=models.CharField(help_text='Human-readable name of the basin.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Spatial information about station.', null=True, srid=3857),
        ),
    ]
