# Generated by Django 2.1.5 on 2019-03-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_timeslots'),
        ('pmo', '0006_weatherstation_basin_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='watercourseobservation',
            name='time_slots',
            field=models.ForeignKey(default=None, help_text='Time_slots used to calc aggregations', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pmo_watercourseobservation_related', to='common.TimeSlots'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='time_slots',
            field=models.ForeignKey(default=None, help_text='Time_slots used to calc aggregations', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pmo_weatherobservation_related', to='common.TimeSlots'),
        ),
        migrations.AlterUniqueTogether(
            name='watercourseobservation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weatherobservation',
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name='weatherobservation',
            options={
                'ordering': ['-phenomenon_time_range', 'feature_of_interest', 'procedure', 'observed_property'],
                'get_latest_by': 'phenomenon_time_range',
            },
        ),
    ]
