# Generated by Django 2.1.5 on 2019-03-25 14:08

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0007_add_timeslots_delete_unique'),
    ]

    operations = [
        migrations.RunSQL("""
        	DELETE FROM pmo_watercourseobservation_related_observations 
				WHERE from_watercourseobservation_id IN (
				    SELECT id FROM pmo_watercourseobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM pmo_watercourseobservation_related_observations 
				WHERE to_watercourseobservation_id IN (
				    SELECT id FROM pmo_watercourseobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM pmo_watercourseobservation WHERE procedure_id IN (
			    SELECT id FROM common_process WHERE name_id IN (
			        'apps.common.aggregate.sum_total', 
			        'apps.common.aggregate.circle_mean', 
			        'apps.common.aggregate.arithmetic_mean', 
			        'avg_day',
			        'avg_hour'
			    )
			);
        """),
        migrations.RunSQL("""
           	CREATE UNIQUE INDEX pmo_watercourseobservation_uniq ON pmo_watercourseobservation
			    (
			        phenomenon_time_range, 
			        observed_property_id, 
			        feature_of_interest_id, 
			        procedure_id, 
			        COALESCE(time_slots_id, -1)
			    );
        """),



         migrations.RunSQL("""
        	DELETE FROM pmo_weatherobservation_related_observations 
				WHERE from_weatherobservation_id IN (
				    SELECT id FROM pmo_weatherobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM pmo_weatherobservation_related_observations 
				WHERE to_weatherobservation_id IN (
				    SELECT id FROM pmo_weatherobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM pmo_weatherobservation WHERE procedure_id IN (
			    SELECT id FROM common_process WHERE name_id IN (
			        'apps.common.aggregate.sum_total', 
			        'apps.common.aggregate.circle_mean', 
			        'apps.common.aggregate.arithmetic_mean', 
			        'avg_day',
			        'avg_hour'
			    )
			);
        """),
        migrations.RunSQL("""
               	CREATE UNIQUE INDEX pmo_weatherobservation_uniq ON pmo_weatherobservation
    			    (
    			        phenomenon_time_range, 
    			        observed_property_id, 
    			        feature_of_interest_id, 
    			        procedure_id, 
    			        COALESCE(time_slots_id, -1)
    			    );
            """),
    ]
