# Generated by Django 2.0.3 on 2018-06-02 14:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventobservation',
            name='point_geometry',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Spatial information about event observation.', null=True, srid=3857),
        ),
    ]
