# Generated by Django 2.0.3 on 2018-06-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0002_eventobservation_point_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(help_text='ID of custom category', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Name of custom category', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='custom_group',
            field=models.ForeignKey(help_text='Custom category of an event.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rsd_custom_group', to='rsd.CategoryCustomGroup'),
        ),
    ]
