# Generated by Django 2.0.3 on 2018-06-17 17:17

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_property_default_mean'),
        ('rsd', '0004_eventobservation_provider_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfEventsObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenomenon_time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='Datetime range when the observation was captured.')),
                ('result', models.DecimalField(decimal_places=3, editable=False, help_text='Numerical value of the measured phenomenon in units specified by Process.', max_digits=8, null=True)),
                ('result_null_reason', models.CharField(default='', help_text='Reason why result is null.', max_length=100)),
                ('category_custom_group', models.ForeignKey(help_text='Custom category of number of event observation', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rsd_number_of_events_observation', to='rsd.CategoryCustomGroup')),
                ('feature_of_interest', models.ForeignKey(help_text='Admin unit of number of event observation', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rsd_number_of_events_observation', to='rsd.AdminUnit')),
                ('observed_property', models.ForeignKey(editable=False, help_text='Phenomenon that was observed, e.g. air temperature.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rsd_numberofeventsobservation_related', to='common.Property')),
                ('procedure', models.ForeignKey(editable=False, help_text='Process used to generate the result, e.g. measurement or average.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rsd_numberofeventsobservation_related', to='common.Process')),
                ('related_observations', models.ManyToManyField(editable=False, help_text='Measured observations that were used to generate average observation, or vice versa.', related_name='_numberofeventsobservation_related_observations_+', to='rsd.NumberOfEventsObservation')),
            ],
        ),
        migrations.AddField(
            model_name='eventextent',
            name='name_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique and computer-friendly name of the extent', max_length=30, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='numberofeventsobservation',
            unique_together={('phenomenon_time_range', 'observed_property', 'feature_of_interest', 'procedure', 'category_custom_group')},
        ),
    ]
