# Generated by Django 2.0.3 on 2018-09-04 17:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0008_created_updated_notnull'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the station.', max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(help_text='Spatial information about feature.', null=True, srid=3857)),
                ('road_number', models.CharField(editable=False, help_text='Road number.', max_length=50)),
                ('road_class', models.CharField(editable=False, help_text='Road class.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the station.', max_length=50)),
                ('id_by_provider', models.CharField(editable=False, help_text='ID of the street used by provider.', max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(help_text='Spatial information about feature.', null=True, srid=3857)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='road',
            unique_together={('road_number', 'road_class')},
        ),
        migrations.AddField(
            model_name='eventobservation',
            name='road',
            field=models.ManyToManyField(related_name='rsd_streets', to='rsd.Road'),
        ),
        migrations.AddField(
            model_name='eventobservation',
            name='street',
            field=models.ManyToManyField(related_name='rsd_streets', to='rsd.Street'),
        ),
    ]
