# Generated by Django 2.1.5 on 2019-03-25 14:08

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0011_add_timeslots_delete_unique'),
    ]

    operations = [
        migrations.RunSQL("""
        	DELETE FROM rsd_eventobservation_related_observations 
				WHERE from_eventobservation_id IN (
				    SELECT id FROM rsd_eventobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM rsd_eventobservation_related_observations 
				WHERE to_eventobservation_id IN (
				    SELECT id FROM rsd_eventobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM rsd_eventobservation WHERE procedure_id IN (
			    SELECT id FROM common_process WHERE name_id IN (
			        'apps.common.aggregate.sum_total', 
			        'apps.common.aggregate.circle_mean', 
			        'apps.common.aggregate.arithmetic_mean', 
			        'avg_day',
			        'avg_hour'
			    )
			);
        """),
        migrations.RunSQL("""
        	CREATE UNIQUE INDEX rsd_eventobservation_uniq ON rsd_eventobservation
			    (
			        phenomenon_time_range, 
			        observed_property_id, 
			        feature_of_interest_id, 
			        procedure_id, 
                    id_by_provider,
                    category_id,
			        COALESCE(time_slots_id, -1)
			    );
        """),






        migrations.RunSQL("""
        	DELETE FROM rsd_numberofeventsobservation_related_observations 
				WHERE from_numberofeventsobservation_id IN (
				    SELECT id FROM rsd_numberofeventsobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM rsd_numberofeventsobservation_related_observations 
				WHERE to_numberofeventsobservation_id IN (
				    SELECT id FROM rsd_numberofeventsobservation WHERE procedure_id IN (
				        SELECT id FROM common_process WHERE name_id IN (
				            'apps.common.aggregate.sum_total', 
				            'apps.common.aggregate.circle_mean', 
				            'apps.common.aggregate.arithmetic_mean', 
				            'avg_day',
				            'avg_hour'
				        )
				    )
				);
        """),
        migrations.RunSQL("""
        	DELETE FROM rsd_numberofeventsobservation WHERE procedure_id IN (
			    SELECT id FROM common_process WHERE name_id IN (
			        'apps.common.aggregate.sum_total', 
			        'apps.common.aggregate.circle_mean', 
			        'apps.common.aggregate.arithmetic_mean', 
			        'avg_day',
			        'avg_hour'
			    )
			);
        """),
        migrations.RunSQL("""
        	CREATE UNIQUE INDEX rsd_numberofeventsobservation_uniq ON rsd_numberofeventsobservation
			    (
			        phenomenon_time_range, 
			        observed_property_id, 
			        feature_of_interest_id, 
			        procedure_id, 
                    category_custom_group_id,
			        COALESCE(time_slots_id, -1)
			    );
        """),
    ]
