# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 19:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_ala_properties_processes'),
        ('o2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioDemoObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenomenon_time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='Datetime range when the observation was captured.')),
                ('age', django.contrib.postgres.fields.ranges.IntegerRangeField(editable=False, help_text='Age of the population.')),
                ('gender', models.CharField(choices=[('-', 'Any'), ('m', 'Male'), ('f', 'Female')], default='-', editable=False, help_text='Gender of the population.', max_length=1)),
                ('occurrence_type', models.CharField(choices=[('0', 'Any'), ('1', 'Transit'), ('2', 'Visit')], editable=False, help_text='Occurrence type in the ZSJ.', max_length=1)),
                ('result', models.PositiveIntegerField(editable=False, help_text='Numerical value of the measured phenomenon in units specified by Process.', null=True)),
                ('result_null_reason', models.CharField(default='', help_text='Reason why result is null.', max_length=100)),
                ('feature_of_interest', models.ForeignKey(editable=False, help_text='ZSJ where the observation was taken.', on_delete=django.db.models.deletion.CASCADE, to='o2.Zsj')),
                ('observed_property', models.ForeignKey(editable=False, help_text='Phenomenon that was observed, e.g. air temperature.', on_delete=django.db.models.deletion.CASCADE, related_name='o2_sociodemoobservation_related', to='common.Property')),
                ('procedure', models.ForeignKey(editable=False, help_text='Process used to generate the result, e.g. measurement or average.', on_delete=django.db.models.deletion.CASCADE, related_name='o2_sociodemoobservation_related', to='common.Process')),
                ('related_observations', models.ManyToManyField(editable=False, help_text='Measured observations that were used to generate average observation, or vice versa.', related_name='_sociodemoobservation_related_observations_+', to='o2.SocioDemoObservation')),
            ],
            options={
                'ordering': ['-phenomenon_time_range', 'feature_of_interest', 'observed_property', 'procedure', 'age', 'gender', 'occurrence_type'],
                'get_latest_by': 'phenomenon_time_range',
            },
        ),
        migrations.AlterField(
            model_name='mobilityobservation',
            name='feature_of_interest',
            field=models.ForeignKey(editable=False, help_text='Stream station where the observation was taken.', on_delete=django.db.models.deletion.CASCADE, to='o2.MobilityStream'),
        ),
        migrations.AlterField(
            model_name='mobilityobservation',
            name='observed_property',
            field=models.ForeignKey(editable=False, help_text='Phenomenon that was observed, e.g. mobility.', on_delete=django.db.models.deletion.CASCADE, to='o2.Property'),
        ),
        migrations.AlterField(
            model_name='mobilityobservation',
            name='procedure',
            field=models.ForeignKey(editable=False, help_text='Process used to generate the result, e.g. estimation.', on_delete=django.db.models.deletion.CASCADE, to='o2.Process'),
        ),
        migrations.AlterUniqueTogether(
            name='sociodemoobservation',
            unique_together=set([('phenomenon_time_range', 'observed_property', 'feature_of_interest', 'procedure', 'age', 'gender', 'occurrence_type')]),
        ),
    ]