# Generated by Django 2.0.3 on 2018-03-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_o2_mobility_properties_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='aggregation',
            field=models.CharField(default='avg', help_text='Name of function used for values aggregation', max_length=30),
        ),
    ]
