# Generated by Django 2.0.3 on 2018-04-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_o2_mobility_properties_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_mean',
            field=models.ForeignKey(editable=False, help_text='Process aggregation used to calculate the result.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='common_property_related', to='common.Process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name_id',
            field=models.CharField(editable=False, help_text="Unique and computer-friendly name of the process. eg. ('measure' or 'avg_hour')", max_length=100, unique=True),
        ),
    ]
