# Generated by Django 2.0.3 on 2018-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_o2_mobility_properties_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_mean',
            field=models.CharField(default='apps.common.aggregate.arithmetic_mean', help_text='Mean calculation module python path', max_length=100),
        ),
    ]
