# Generated by Django 2.0.3 on 2018-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_o2_mobility_properties_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_average',
            field=models.CharField(default='apps.common.aggregate.avg', help_text='Average calculation module python path', max_length=100),
        ),
    ]
