# Generated by Django 2.0.3 on 2018-03-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_property_aggregation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='aggregation',
            new_name='agg_function',
        ),
        migrations.AddField(
            model_name='property',
            name='agg_module',
            field=models.CharField(default='apps.common.aggregate', help_text='Name of aggregation module', max_length=100),
        ),
    ]
