# Generated by Django 2.0.3 on 2018-08-23 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_time_range_custom_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(help_text="Unique and computer-friendly name of the topic. eg. ('drought')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name of the topic.', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'topics',
                'ordering': ['name'],
            },
        )
    ]
