# Generated by Django 2.1.5 on 2019-03-25 16:12

import apps.common.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import relativedeltafield


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_timeseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the time_slots.', max_length=50)),
                ('name_id', models.CharField(
                    help_text="Unique and computer-friendly name of time_slots",
                    max_length=100, unique=True)),

                ('zero', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=utc))),
                ('frequency', relativedeltafield.RelativeDeltaField(default=apps.common.models.default_relative_delta_hour)),
                ('range_from', relativedeltafield.RelativeDeltaField(default=apps.common.models.default_relative_delta_zero)),
                ('range_to', relativedeltafield.RelativeDeltaField(default=apps.common.models.default_relative_delta_hour)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSeries',
        ),
    ]
