# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ala', '0002_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='feature_of_interest',
            field=models.ForeignKey(editable=False,
                                    help_text='Weather station where the observation was taken.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='observations',
                                    to='ala.SamplingFeature'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_property',
            field=models.ForeignKey(editable=False,
                                    help_text='Phenomenon that was observed, e.g. air temperature.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='observations',
                                    to='ala.Property'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='phenomenon_time',
            field=models.DateTimeField(editable=False,
                                       help_text='Beginning of the observation.'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='phenomenon_time_to',
            field=models.DateTimeField(editable=False,
                                       help_text='End of the observation. If the observation was instant, it is the same time as phenomenon_time.'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='procedure',
            field=models.ForeignKey(editable=False,
                                    help_text='Process used to generate the result, e.g. measurement or average.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='observations',
                                    to='ala.Process'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='related_observations',
            field=models.ManyToManyField(editable=False,
                                         help_text='Measured observations that were used to generate average observation, or vice versa.',
                                         related_name='_observation_related_observations_+',
                                         to='ala.Observation'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='result',
            field=models.DecimalField(decimal_places=3, editable=False,
                                      help_text='Numerical value of the measured phenomenon in units specified by Process.',
                                      max_digits=8),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(
                help_text='Human-readable name of the process.',
                max_length=50),
        ),
        migrations.AlterField(
            model_name='process',
            name='name_id',
            field=models.CharField(editable=False,
                                   help_text='Unique and computer-friendly name of the process.',
                                   max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(
                help_text='Human-readable name of the property.',
                max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='name_id',
            field=models.CharField(editable=False,
                                   help_text='Unique and computer-friendly name of the property.',
                                   max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit',
            field=models.CharField(
                help_text='Unit of observations (physical unit). Same for all observations of the property.',
                max_length=30),
        ),
        migrations.AlterField(
            model_name='samplingfeature',
            name='id_by_provider',
            field=models.CharField(editable=False,
                                   help_text='ID of the station used by provider (ALA).',
                                   max_length=50),
        ),
        migrations.AlterField(
            model_name='samplingfeature',
            name='name',
            field=models.CharField(
                help_text='Human-readable name of the station.',
                max_length=50),
        ),
    ]
