# Generated by Django 2.0.2 on 2018-02-13 23:43

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ala', '0007_phenomenon_time_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='feature_of_interest',
            field=models.ForeignKey(editable=False, help_text='Weather station where the observation was taken.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='observations', to='ala.SamplingFeature'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_property',
            field=models.ForeignKey(editable=False, help_text='Phenomenon that was observed, e.g. air temperature.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ala_observation_related', to='common.Property'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='phenomenon_time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='Datetime range when the observation was captured.'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='procedure',
            field=models.ForeignKey(editable=False, help_text='Process used to generate the result, e.g. measurement or average.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ala_observation_related', to='common.Process'),
        ),
    ]
