# Generated by Django 2.0.3 on 2018-06-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ala', '0009_samplingfeature_geometry'),
    ]

    operations = [
        migrations.RunSQL("UPDATE ala_observation "
                          "SET procedure_id = ("
                            "SELECT id "
                            "FROM public.common_process "
                            "WHERE name_id = 'apps.common.aggregate.arithmetic_mean') "
                          "WHERE procedure_id = ("
                            "SELECT id "
                            "FROM public.common_process "
                            "WHERE name_id = 'avg_hour')"
                          )
    ]
