# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenomenon_time', models.DateTimeField()),
                ('result', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SamplingFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='feature_of_interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='ala.SamplingFeature'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observed_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='ala.Property'),
        ),
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together=set([('phenomenon_time', 'observed_property', 'feature_of_interest')]),
        ),
    ]
