# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'processes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'get_latest_by': 'phenomenon_time', 'ordering': ['-phenomenon_time', 'feature_of_interest', 'procedure', 'observed_property']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelOptions(
            name='samplingfeature',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='samplingfeature',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='observation',
            name='phenomenon_time_to',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='related_observations',
            field=models.ManyToManyField(editable=False, related_name='_observation_related_observations_+', to='ala.Observation'),
        ),
        migrations.AddField(
            model_name='samplingfeature',
            name='id_by_provider',
            field=models.CharField(default='', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='feature_of_interest',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='ala.SamplingFeature'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_property',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='ala.Property'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='phenomenon_time',
            field=models.DateTimeField(editable=False, help_text='Time that the result applies to the property of the feature-of-interest. This is often the time of interaction by a sampling procedure or observation procedure with a real-world feature.'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='result',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='property',
            name='name_id',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='procedure',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='ala.Process'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together=set([('phenomenon_time', 'phenomenon_time_to', 'observed_property', 'feature_of_interest', 'procedure')]),
        ),
    ]
