# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def correct_data_from_sql():
    sql_statements = """
BEGIN;

LOCK TABLE public.ala_process IN EXCLUSIVE MODE;
LOCK TABLE public.ala_observation IN EXCLUSIVE MODE;

ALTER TABLE public.ala_observation DROP CONSTRAINT ala_observation_procedure_id_2990e93f_fk_ala_process_id;

ALTER TABLE public.ala_observation
  ADD CONSTRAINT ala_observation_procedure_id_2990e93f_fk_ala_process_id FOREIGN KEY (procedure_id)
      REFERENCES public.ala_process (id) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
END;

BEGIN;

LOCK TABLE public.ala_process IN EXCLUSIVE MODE;
LOCK TABLE public.ala_observation IN EXCLUSIVE MODE;

UPDATE public.ala_process as A
SET id = B.id
FROM public.common_process as B
WHERE A.name_id = B.name_id;
END;

BEGIN;

LOCK TABLE public.ala_process IN EXCLUSIVE MODE;
LOCK TABLE public.ala_observation IN EXCLUSIVE MODE;

ALTER TABLE public.ala_observation DROP CONSTRAINT ala_observation_procedure_id_2990e93f_fk_ala_process_id;

ALTER TABLE public.ala_observation
  ADD CONSTRAINT ala_observation_procedure_id_2990e93f_fk_ala_process_id FOREIGN KEY (procedure_id)
      REFERENCES public.ala_process (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
END;


BEGIN;

LOCK TABLE public.ala_property IN EXCLUSIVE MODE;
LOCK TABLE public.ala_observation IN EXCLUSIVE MODE;

ALTER TABLE public.ala_observation DROP CONSTRAINT ala_observation_observed_property_id_98d33b43_fk_ala_prope;
ALTER TABLE public.ala_observation
  ADD CONSTRAINT ala_observation_observed_property_id_98d33b43_fk_ala_prope FOREIGN KEY (observed_property_id)
      REFERENCES public.ala_property (id) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
END;

BEGIN;

LOCK TABLE public.ala_property IN EXCLUSIVE MODE;
LOCK TABLE public.ala_observation IN EXCLUSIVE MODE;

UPDATE public.ala_property as A
SET id = B.id
FROM public.common_property as B
WHERE A.name_id = B.name_id;
END;

BEGIN;

LOCK TABLE public.ala_property IN EXCLUSIVE MODE;
LOCK TABLE public.ala_observation IN EXCLUSIVE MODE;

ALTER TABLE public.ala_observation DROP CONSTRAINT ala_observation_observed_property_id_98d33b43_fk_ala_prope;

ALTER TABLE public.ala_observation
  ADD CONSTRAINT ala_observation_observed_property_id_98d33b43_fk_ala_prope FOREIGN KEY (observed_property_id)
      REFERENCES public.ala_property (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
END;

"""
    return sql_statements


def ignore_data_from_sql():
    return ''


class Migration(migrations.Migration):

    dependencies = [
        ('ala', '0003_improve_doc'),
        ('common', '0002_ala_properties_processes'),
    ]

    operations = [
        migrations.RunSQL(correct_data_from_sql(), ignore_data_from_sql()),
        migrations.AlterField(
            model_name='observation',
            name='observed_property',
            field=models.ForeignKey(editable=False, help_text='Phenomenon that was observed, e.g. air temperature.', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='common.Property'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='procedure',
            field=models.ForeignKey(editable=False, help_text='Process used to generate the result, e.g. measurement or average.', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='common.Process'),
        ),
        migrations.AlterField(
            model_name='samplingfeature',
            name='id_by_provider',
            field=models.CharField(editable=False, help_text='ID of the station used by provider.', max_length=50),
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
