# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ala', '0004_common_property_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observed_property',
            field=models.ForeignKey(editable=False, help_text='Phenomenon that was observed, e.g. air temperature.', on_delete=django.db.models.deletion.CASCADE, related_name='ala_observation_related', to='common.Property'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='procedure',
            field=models.ForeignKey(editable=False, help_text='Process used to generate the result, e.g. measurement or average.', on_delete=django.db.models.deletion.CASCADE, related_name='ala_observation_related', to='common.Process'),
        ),
    ]